services:
    # the external mailchimp api that we are using
    mailmotor.mailchimp.api:
        class: Mailchimp\Mailchimp
        arguments:
            - "%mailmotor.api_key%"

    # all gateways must have this service naming convention
    mailmotor.mailchimp.gateway:
        class: MailMotor\Bundle\MailChimpBundle\Component\MailChimpGateway
        arguments:
            - "@mailmotor.mailchimp.api"
            - "%mailmotor.list_id%"
