services:
    mailchimp.service:
        class: MailMotor\Bundle\MailChimpBundle\Component\MailChimpService
        arguments:
            - "%mailmotor.mailchimp.api_key%"
            - "%mailmotor.mailchimp.list_id%"