services:
    # gateways
    mailmotor.mailchimp.subscriber.gateway:
        class: MailMotor\Bundle\MailChimpBundle\Gateway\MailChimpSubscriberGateway
        arguments:
            - "%mailmotor.api_key%"
        tags:
            - { name: mailmotor.subscriber_gateway, alias: mailchimp }
